// <auto-generated />
using System;
using ExamenProject_Patrick;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamenProject_Patrick.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20231115194254_Gebruiker")]
    partial class Gebruiker
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExamenProject_Patrick.Models.Afspraak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OnderwerpId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OnderwerpId");

                    b.ToTable("Afspraken");
                });

            modelBuilder.Entity("ExamenProject_Patrick.Models.Onderwerp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Onderwerpen");
                });

            modelBuilder.Entity("ExamenProject_Patrick.Models.Afspraak", b =>
                {
                    b.HasOne("ExamenProject_Patrick.Models.Onderwerp", "Onderwerp")
                        .WithMany("Afspraken")
                        .HasForeignKey("OnderwerpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Onderwerp");
                });

            modelBuilder.Entity("ExamenProject_Patrick.Models.Onderwerp", b =>
                {
                    b.Navigation("Afspraken");
                });
#pragma warning restore 612, 618
        }
    }
}
